create table if not exists public.visit_requests (
  id bigint generated by default as identity primary key,
  visitor_name text not null check (char_length(visitor_name) between 1 and 100),
  visitor_email text not null,
  visit_date date not null,
  notes text not null check (char_length(notes) <= 2000),
  created_at timestamptz not null default now()
);

create or replace function public.validate_visit_request_email()
returns trigger
language plpgsql
as $$
begin
  if new.visitor_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'Invalid email address';
  end if;

  return new;
end;
$$;

drop trigger if exists visit_requests_validate_email on public.visit_requests;

create trigger visit_requests_validate_email
before insert or update on public.visit_requests
for each row
execute function public.validate_visit_request_email();
